### ISSUE TITLE
FreeBSD 12 - installation fails

### ISSUE THREAD

**Issue by spagu** [clonos/clonos-ports-wip#4]
after doing `env workdir=/usr/jails/cbsd/ /usr/local/cbsd/sudoexec/initenv`

I cannot start cbsdd
```
#service cbsdd status || service cbsdd start
cbsd: no such /usr/jails/cbsd/cbsd.conf
cbsd: no such /usr/jails/cbsd/cbsd.conf
```
based on documentation: https://clonos.tekroutine.com/installation_on_freebsd.html

**Comment by olevole** [comment]
this should be fixed in the latest CBSD version (12.0.12)

which one do you use? (cbsd version) ?

Unfortunately, the ClonOS code is currently out of sync with latest CBSD

**Comment by spagu** [comment]
cbsd-12.0.12 from official FreeBSD12 packages.

**Comment by spagu** [comment]
Any reason that this is not included into official ports tree?

**Comment by olevole** [comment]
The port is still of poor quality and needs some improvement.  Besides this, the work on the ClonOS is rather slow due to the lack of man power =) I am mainly focused on backend size - CBSD.

as for `cbsd: no such /usr/jails/cbsd/cbsd.conf` this seems to be a CBSD problem. Can you paste the contents of cbsdd from your host:
```
cat /usr/local/etc/rc.d/cbsdd
```

?

**Comment by spagu** [comment]
Here is a file: https://pastebin.com/364pt84Q that indicates this is an incomplete(old) version. 

Did moved the ticket to https://github.com/cbsd/cbsd/issues/416  as nothing more can be done here. 

"_https://pkg.freebsd.org/FreeBSD:12:amd64/latest/All/cbsd-12.0.12.txz 
https://pkg.freebsd.org/FreeBSD:12:amd64/quarterly/All/cbsd-12.0.12.txz
there are two different packages_"

Thanks for the help.
